service: helloworld-typescript

provider:
  name: aws
  runtime: nodejs16.x

functions:
  helloWorldFunction:
    handler: handler.hello
    name: hello-world-typescript
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /hello
          method: get
      
plugins:
  - serverless-plugin-typescript
  - serverless-offline